### PR TITLE
Removes duplicated webcam recording code

### PR DESCRIPTION
**Pull request by juho-jaakkola**

### CODE REVIEW

**Comment by gerard-kanters** [comment]
Did you check if this code wasn't use for a specific purpose ? I believe there was a need for this to allow the webcam to be used in registration page.

**Comment by juho-jaakkola** [comment]
I don't know about any specific purpose, but it still works fine both on avatar editing page and registration page.

**Comment by juho-jaakkola** [comment]
I'll re-check the commit logs once more in case there is a mention about it.

**Comment by juho-jaakkola** [comment]
It seems to me that the current code takes both forms into consideration:
 - https://github.com/Centillien/webcam/blob/43cbb24b52222f2d1ce5143dc957df7d1fa226fe/views/default/js/webcam.php#L28-L29
 - https://github.com/Centillien/webcam/blob/43cbb24b52222f2d1ce5143dc957df7d1fa226fe/haxe/ElggWebcamPlugin.hx#L83-L84

**Pull request merged**
